Catalogue/Catalogue.Web/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Catalogue.Models.Entities;
using Catalogue.Models.Services;
using Catalogue.Web.Models;

namespace Catalogue.Web.Controllers
{
    public class CategoryController : Controller
    {
        private ICategoryService categoryServices;

        public CategoryController(ICategoryService categoryServices)
        {
            this.categoryServices = categoryServices;
        }

        public ActionResult Index(int? page)
        {
            var pageItems = categoryServices.GetItems(page);

            var categoryListViewModel = new CategoryListViewModel()
            {
                Categories = pageItems.Items.ToList(),
                Count = pageItems.PageCount,
                Page = pageItems.CurrentPage
            };

            return View(categoryListViewModel);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CategoryViewModel model)
        {
            if (ModelState.IsValid)
            {
                var category = new Category()
                {
                    CategoryID = model.CategoryID,
                    Name = model.Name
                };

                categoryServices.Add(category);

                return RedirectToAction("Index");
            }

            return View(model);
        }

        public ActionResult LoadCategories()
        {
            List<SelectListItem> categoriesList = new List<SelectListItem>();

            var categories = categoryServices.GetAll();

            foreach (var item in categories)
            {
                categoriesList.Add(new SelectListItem { Text = item.Name, Value = item.CategoryID.ToString() });
            }

            ViewData["categories"] = categoriesList;

            return PartialView("_CategoriesPartial");
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = categoryServices.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }

            var model = new CategoryViewModel()
            {
                CategoryID = category.CategoryID,
                Name = category.Name
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CategoryViewModel model)
        {
            if (ModelState.IsValid)
            {
                var category = new Category()
                {
                    CategoryID = model.CategoryID,
                    Name = model.Name
                };

                categoryServices.Modify(category);

                return RedirectToAction("Index");
            }
            return View(model);
        }

        // GET: /Category/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = categoryServices.Find(id);

            if (category == null)
            {
                return HttpNotFound();
            }

            var model = new CategoryViewModel()
            {
                CategoryID = category.CategoryID,
                Name = category.Name
            };
            return View(model);
        }

        // POST: /Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = categoryServices.Find(id);

            categoryServices.Remove(category);

            return RedirectToAction("Index");
        }
    }
}

Catalogue/Catalogue.Web/Controllers/ManufacturerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Catalogue.Models.Entities;
using Catalogue.Models.Services;
using Catalogue.Web.Models;

namespace Catalogue.Web.Controllers
{
    public class ManufacturerController : Controller
    {
        private IManufacturerService manufacturerServices;

        public ManufacturerController(IManufacturerService manufacturerServices)
        {
            this.manufacturerServices = manufacturerServices;
        }

        public ActionResult Index(int? page)
        {
            var pageItems = manufacturerServices.GetItems(page);

            var manufacturerListViewModel = new ManufacturerListViewModel()
            {
                Manufacturers = pageItems.Items.ToList(),
                Count = pageItems.PageCount,
                Page = pageItems.CurrentPage
            };

            return View(manufacturerListViewModel);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ManufacturerViewModel model)
        {
            if (ModelState.IsValid)
            {
                var manufacturer = new Manufacturer()
                {
                    ManufacturerID = model.ManufacturerID,
                    Name = model.Name,
                    Description = model.Description
                };

                manufacturerServices.Add(manufacturer);

                return RedirectToAction("Index");
            }

            return View(model);
        }

        public ActionResult LoadManufacturers()
        {
            List<SelectListItem> manufacturersList = new List<SelectListItem>();

            var manufacturers = manufacturerServices.GetAll();

            foreach (var item in manufacturers)
            {
                manufacturersList.Add(new SelectListItem { Text = item.Name, Value = item.ManufacturerID.ToString() });
            }

            ViewData["manufacturers"] = manufacturersList;

            return PartialView("_ManufacturersPartial");
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var manufacturer = manufacturerServices.Find(id);

            if (manufacturer == null)
            {
                return HttpNotFound();
            }

            var model = new ManufacturerViewModel()
            {
                ManufacturerID = manufacturer.ManufacturerID,
                Name = manufacturer.Name,
                Description = manufacturer.Description
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ManufacturerViewModel model)
        {
            if (ModelState.IsValid)
            {
                var manufacturer = new Manufacturer()
                {
                    ManufacturerID = model.ManufacturerID,
                    Name = model.Name,
                    Description = model.Description
                };

                manufacturerServices.Modify(manufacturer);

                return RedirectToAction("Index");
            }
            return View(model);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var manufacturer = manufacturerServices.Find(id);

            if (manufacturer == null)
            {
                return HttpNotFound();
            }

            var model = new ManufacturerViewModel()
            {
                Name = manufacturer.Name,
                Description = manufacturer.Description
            };

            return View(model);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var manufacturer = manufacturerServices.Find(id);
            manufacturerServices.Remove(manufacturer);

            return RedirectToAction("Index");
        }
    }
}

Catalogue/Catalogue.Web/Controllers/ProductController.cs
using Catalogue.Models.Entities;
using Catalogue.Models.Services;
using Catalogue.Web.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Catalogue.Web.Controllers
{
    public class ProductController : Controller
    {
        private IProductService productServices;

        public ProductController(IProductService productServices)
        {
            this.productServices = productServices;
        }

        public ActionResult ProductsList(int? page)
        {
            var pageItems = productServices.GetItems(page);

            var productListViewModels = new ProductListViewModels()
            {
                Products = pageItems.Items.ToList(),
                Count = pageItems.PageCount,
                Page = pageItems.CurrentPage
            };

            return View(productListViewModels);
        }

        [HttpGet]
        public ActionResult Save()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult Save(ProductViewModel model, Image img)
        {
            if (ModelState.IsValid)
            {
                var images = new List<Image>();

                foreach (var item in model.Files)
                {
                    if (item != null)
                    {
                        RenderImage service = new RenderImage();
                        service.RenderImg(img, item);
                        var rndrResizedImage = service.ResizeFile(img);
                        images.Add(rndrResizedImage);
                    }

                }

                var product = new Product()
                {
                    Category = model.Category,
                    CategoryID = model.CategoryID,
                    Description = model.Description,
                    Manufacturers = model.Manufacturers,
                    Name = model.Name,
                    ProductYear = model.ProductYear,
                    Images = images
                };

                productServices.Add(product);
                return RedirectToAction("ProductsList");
            }
            return View();
        }

        public ActionResult GetYears()
        {
            List<int> years = new List<int>();
            var currentYear = DateTime.Now.Year;
            years.Add(currentYear + 1);

            for (int i = 0; i < 30; i++)
            {
                years.Add(currentYear - i);
            }

            return PartialView("_YearsPartial", years);
        }
    }
}

Catalogue/Catalogue.Web/Views/Shared/_CategoriesPartial.cshtml
@model Product

<div class="form-group">
    <label class="control-label col-md-2" for="@Html.IdFor(x => x.Category)">Category<span class="required">*</span></label>
        <div class="col-md-10">
            @Html.DropDownListFor(x => x.Category.Name, ViewData["categories"] as List<SelectListItem>, "Choose...", new { @class = "form-control" })
            @Html.ValidationMessageFor(x => x.Category.Name, "Category is required.")
        </div>
    </div>

Catalogue/Catalogue.Web/Views/Shared/_IsInRolePartial.cshtml
@model UserViewModels

@if (Model.isAdmin)
{
    <td>
        <img src="~/fonts/glyphicons_193_circle_ok.png" />
    </td>
}
else
{
    <td>
        <img src="~/fonts/glyphicons_192_circle_remove.png" />
    </td>
}

@if (Model.isManager)
{
    <td>
        <img src="~/fonts/glyphicons_193_circle_ok.png" />
    </td>
}
else
{
    <td>
        <img src="~/fonts/glyphicons_192_circle_remove.png" />
    </td>
}

@if (Model.isModerator)
{
    <td>
        <img src="~/fonts/glyphicons_193_circle_ok.png" />
    </td>
}
else
{
    <td>
        <img src="~/fonts/glyphicons_192_circle_remove.png" />
    </td>
}

Catalogue/Catalogue.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Catalogue System</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Catalogue System", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @*@if (User.IsInRole("Admin"))
                        {*@
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Administration <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Products", "ProductsList", "Product")</li>
                            <li>@Html.ActionLink("Manufacturers", "Index", "Manufacturer")</li>
                            <li>@Html.ActionLink("Categories", "Index", "Category")</li>
                            <li>@Html.ActionLink("Users", "Users", "Admin")</li>
                        </ul>
                    </li>

                    @*}*@
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p class="footer">&copy; @DateTime.Now.Year - Team Acer</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Catalogue/Catalogue.Web/Views/Shared/_ManufacturersPartial.cshtml
@model Product

<div class="form-group">
    <label class="control-label col-md-2" for="@Html.IdFor(x => x.Manufacturers)">Manufacturers<span class="required">*</span></label>
    <div class="col-md-10">
        @Html.DropDownListFor(x => x.Manufacturers.Name, ViewData["manufacturers"] as List<SelectListItem>, "Choose...", new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.Manufacturers.Name, "Manufacturer is required.")
    </div>
</div>

Catalogue/Catalogue.Web/Views/Shared/_YearsPartial.cshtml
@model IEnumerable<int>

<div class="row form-group">
    @Html.Label("Year of production", new { @class = "col-md-2 control-label" })
    <div class="col-md-10">
        <div class="editor-field">
            @Html.DropDownList("ProductYear", new SelectList(@Model))
        </div>
    </div>
</div>